import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as B from '../web/src/bergman-syntax.js';
import { EXAMPLES } from '../web/src/examples.js';

test('relations round-trip to bergman input form', () => {
  assert.equal(B.toBergman(B.parseRelation('4*x*x-3*y*x+3*x*y-y*y', ['x', 'y'])), '4*x*x-3*y*x+3*x*y-y*y');
  assert.equal(B.toBergman(B.parseRelation('xyx - 2yy', ['x', 'y'])), 'x*y*x-2*y*y');
  assert.equal(B.toBergman(B.parseRelation('a^2-1', ['a'])), 'a^2-1');
});

test('homogeneity, with and without weights', () => {
  assert.equal(B.isHomogeneous(B.parseRelation('a^2-1', ['a']), new Map()), false);
  assert.equal(B.isHomogeneous(B.parseRelation('x*z-y*z', ['x', 'y', 'z']), new Map()), true);
  assert.equal(B.isHomogeneous(B.parseRelation('x*z-y*z', ['x', 'y', 'z']), new Map([['x', 1], ['y', 2], ['z', 2]])), false);
});

test('input bergman cannot read is rejected', () => {
  for (const bad of ['x*(y+1)', 'q*x', '1.5*x', 'x^', 'x+']) {
    assert.throws(() => B.parseRelation(bad, ['x', 'y']), SyntaxError, bad);
  }
});

test('typesetting marks the leading monomial', () => {
  const html = B.typeset('y^2+3*y*x', { lead: true });
  assert.match(html, /^<mark class="lm"><var>y<\/var><sup>2<\/sup><\/mark>/);
});

test('every bundled example parses, and its reference output renders', () => {
  for (const e of EXAMPLES) {
    const st = B.readInputFile(e.input);
    assert.ok(st.vars.length > 0, `${e.id}: generators`);
    for (const r of st.rels) B.parseRelation(r, st.vars);
    assert.ok(B.parseBasis(e.out.gb).groups.length > 0, `${e.id}: basis`);
    if (e.out.anick) assert.ok(B.parseAnick(e.out.anick).table, `${e.id}: Betti table`);
  }
});

test('Bergman 2 families produce valid relations', () => {
  for (const [id, f] of Object.entries(B.FAMILIES)) {
    for (const n of [2, 3, 4]) {
      const { vars, rels } = f.build(n);
      for (const r of rels) B.parseRelation(r, vars);
      assert.ok(rels.length > 0, `${id} n=${n}`);
    }
  }
});

test('legacy mode is passed to bergman', () => {
  const job = B.buildJob({ task: 'ncpbh', ring: 'noncomm', order: 'degleftlex', field: '0', vars: ['x'], rels: ['x^2'], legacy: true, weights: '' });
  assert.ok(job.script.includes('(SETLEGACYMODE T)'));
  assert.equal(job.legacy, true);
});

test('session script for an Anick resolution over F_5', () => {
  const job = B.buildJob({ task: 'anick', ring: 'noncomm', order: 'degleftlex', field: 'p', modulus: 5,
    vars: ['x', 'y'], rels: ['x*y'], maxdeg: 4, weights: '', nonhomog: 'degreewise' });
  assert.equal(job.files['input.bg'], '(ALGFORMINPUT)\nvars x, y;\nx*y;\n');
  assert.deepEqual(job.script.split('\n').filter(Boolean), [
    '% Generated by George', '(SETLEGACYMODE NIL)', '(NONCOMMIFY)', '(DEGLEFTLEXIFY)', '(SETMODULUS 5)', '(SETMAXDEG 4)',
    '(SETQ ANICKRESOLUTIONOUTPUTFILE "result.anick")', '(ANICK "input.bg" "result.gb")',
    '(CALCULATEANICKRESOLUTIONTOLIMIT (GETMAXDEG))', '(ANICKDISPLAY)', '(GEORGEWRITERESOLUTION "resolution.jsonl")', '(CLEARRING)',
  ]);
});
