// Generated by tools/build.sh; do not hand edit.
export const WASM_HASHES={"32": "c82d7c239de53b39b714ebf7de48f6f3f1d8c3197ee65407a2d1e677b88d4878", "32-single": "3e95af0fcd6bfd1d4d3b0d9c2b764770defdfcef11c2a91e31d6ada5afcd7b4f", "64": "75eb6f6e765a2c93cb2df0ccc4ad453ae0f48a18c600c8200f48d4c3e4d8aca2", "64-single": "91b23485de2011692578988fe86bb36f968d41ac98c655684636116093263570"};
