// Generated by tools/build.sh; do not hand edit.
export const WASM_HASHES={"32": "25bde5d74b67bdf971bfd0b86c495f1447c5db968ab15c79fc656b4ebcff4487", "32-single": "f5bfe5d39518c221031fb0b280235b935d7bb65f1a09dbb1d3180db0c1fa2926", "64": "247da1d49f4d7e7b317b4cb9d127faef42aa84613a9df91035873e2ebe1e2b8a", "64-single": "c30065e4e4b7d1cdc7809755f1cb462252f3ea9ce7963afbc1a2f19ef0d4bc8f"};
