// Generated by tools/build.sh; do not hand edit.
export const WASM_HASHES={"32": "acdfdf7be0e6248849d0f329c91260e87fa217cbbc6f6a27e546040569e6618f", "32-single": "3b6416d40a2b9f83042f15cadc14fc60160190d45ecd49d79ccfd0e200c3bfb3", "64": "5cadac3c6a744253de15b4dd2bd3d5b9c04e8bbf8e9f4a3fa381db57b2877a42", "64-single": "4e8dfc5850406106a2f0f551d895c267da506e7ecdc41b6cb70d8a9480e4a073"};
