"""Exact finite-star regular representations from BLM deletion derivatives.

This is a finite-control constructor (at most four leaves), NOT an FK6 completion
algorithm. It selects a basis of derivative images degree-by-degree and checks its
rank against the known finite-star Hilbert polynomial. Agreement certifies the
coordinate model, using the published finite-star dimensions as upper bounds.
All calculations use Fraction. No Groebner basis, stochastic rank or FK6 zero test.
"""
from fractions import Fraction as Q
from itertools import combinations
from .deletion import all_derivatives,reference_all
from .core import permutation_degree
from .series import known_hilbert,divide

def plus(out,p,c=1):
    for k,v in p.items():
        z=out.get(k,0)+c*v
        if z:out[k]=z
        else:out.pop(k,None)
    return out

class ColumnSpace:
    def __init__(self):self.rows={};self.size=0
    def reduce(self,p):
        p={k:Q(v) for k,v in p.items() if v};coords={}
        while p:
            k=max(p)
            if k not in self.rows:break
            v,c=self.rows[k];a=p[k];plus(p,v,-a);plus(coords,c,a)
        return p,coords
    def insert(self,p):
        remainder,coords=self.reduce(p)
        if not remainder:return False,coords
        k=max(remainder);a=remainder[k];i=self.size;self.size+=1
        vec={j:v/a for j,v in remainder.items()};combo={j:-v/a for j,v in coords.items()};combo[i]=1/a
        self.rows[k]=(vec,combo);return True,{i:Q(1)}
    def coordinates(self,p):
        r,c=self.reduce(p)
        if r:raise ValueError('Vector outside certified span')
        return c

def star_hilbert(m):
    if not 0<=m<=4:raise ValueError('Only published finite star dimensions m<=4')
    if not m:return [1]
    H=known_hilbert();h=divide(H[m+1],H[m]);
    while len(h)>1 and h[-1]==0:h.pop()
    return h

class FiniteStar:
    def __init__(self,m,max_degree=None,on_degree=None,independent=False):
        if m not in [1,2,3,4]:raise ValueError('Finite calibration requires 1..4 leaves; FK6 is NOT assumed finite')
        self.m=m;self.n=m+1;self.gens=tuple((i,self.n) for i in range(1,self.n));self.edges=tuple(combinations(range(1,self.n+1),2));self.edge_id={e:i for i,e in enumerate(self.edges)}
        self.expected=star_hilbert(m);self.top=len(self.expected)-1;self.basis=[[()]];self.left=[None];self.spaces=[None];self._cache={():{0:Q(1)}};self.audit=[]
        derive=reference_all if independent else all_derivatives
        limit=self.top+1 if max_degree is None else min(max_degree,self.top+1)
        for d in range(1,limit+1):
            words=[];space=ColumnSpace();matrices=[[] for _ in self.gens];previous=self.basis[-1]
            for gi,g in enumerate(self.gens):
                for w in previous:
                    word=(g,)+w;features={}
                    for e,p in derive({word:1},self.n).items():
                        base=self.edge_id[e]*len(previous)
                        for v,c in p.items():
                            for j,q in self.coordinates(v).items():
                                z=features.get(base+j,0)+c*q
                                if z:features[base+j]=z
                                else:features.pop(base+j,None)
                    accepted,coords=space.insert(features)
                    if accepted:words.append(word)
                    matrices[gi].append(coords)
            expected=self.expected[d] if d<=self.top else 0
            if len(words)!=expected:raise AssertionError(f'Degree {d}: derivative image rank {len(words)} != published dimension {expected}')
            self.basis.append(words);self.left.append(matrices);self.spaces.append(space)
            item={'degree':d,'rank':len(words),'publishedDimension':expected,'candidateColumns':self.m*len(previous),'passed':True};self.audit.append(item)
            if on_degree:on_degree(item)
        self.built_through=limit
    def coordinates(self,w):
        w=tuple(w)
        if w in self._cache:return self._cache[w].copy()
        d=len(w)
        if d>self.top:return {}
        if d>=len(self.left):raise ValueError('Degree not built yet')
        g=self.gens.index(w[0]);out={}
        for i,c in self.coordinates(w[1:]).items():plus(out,self.left[d][g][i],c)
        if len(self._cache)<200000:self._cache[w]=out.copy()
        return out
    def vector(self,p):
        out={}
        for w,c in p.items():plus(out,self.coordinates(w),c)
        return out
    def left_poly(self,p,d,coords):
        out={}
        for i,c in coords.items():
            w=self.basis[d][i]
            for v,a in p.items():plus(out,self.coordinates(v+w),a*c)
        return out
    def subset_words(self,indices,degree):
        """Basis of the subalgebra generated by the selected original letters."""
        current=[()]
        for d in range(1,degree+1):
            space=ColumnSpace();nxt=[]
            for i in indices:
                for w in current:
                    word=(self.gens[i],)+w
                    if space.insert(self.coordinates(word))[0]:nxt.append(word)
            current=nxt
        return current
    def top_word(self,indices):
        d=len(star_hilbert(len(indices)))-1;ws=self.subset_words(indices,d)
        if len(ws)!=1:raise ValueError('Known substar top did not have rank one')
        return ws[0]


def rank(columns):
    S=ColumnSpace()
    for p in columns:S.insert(p)
    return S.size

def kernel(columns):
    """Column relations in the ORIGINAL input coordinates, not pivot coordinates."""
    S=ColumnSpace();independent=[];out=[]
    for j,col in enumerate(columns):
        new,coords=S.insert(col)
        if new:independent.append(j)
        else:
            rel={j:Q(1)}
            for k,v in coords.items():rel[independent[k]]=-v
            out.append({k:v for k,v in rel.items() if v})
    return out

def intersection(A,B):
    columns=A+B;out=[];space=ColumnSpace()
    for k in kernel(columns):
        v={}
        for i,c in k.items():
            if i<len(A):plus(v,A[i],c)
        if v and space.insert(v)[0]:out.append(v)
    return out
