;;; SBCL shims standing in for the CLISP-specific pieces bergman's CL build uses.
(require :sb-posix)
(setf *compile-verbose* nil *compile-print* nil sb-fasl:*fasl-file-type* "fas")
(declaim (sb-ext:muffle-conditions style-warning sb-ext:compiler-note warning))
(sb-ext:unlock-package :common-lisp)
(rename-package "COMMON-LISP" "COMMON-LISP" '("CL" "LISP"))
(defpackage "EXT" (:use "COMMON-LISP")
  (:export "GETENV" "QUIT" "EXIT" "SAVEINITMEM" "GC"))
(in-package "EXT")
(defun getenv (n) (sb-ext:posix-getenv n))
(defun (setf getenv) (v n) (sb-posix:setenv n v 1) v)
(defun quit (&optional (code 0)) (finish-output) (sb-ext:exit :code code :abort t))
(defun exit (&optional (code 0)) (quit code))
(defun gc () (sb-ext:gc :full t))
(defun saveinitmem (file &key init-function executable)
  (declare (ignore executable))
  (push (lambda () (setf *package* (find-package "Bergman"))
                   (when init-function (funcall init-function)))
        sb-ext:*init-hooks*)
  (sb-ext:save-lisp-and-die file :executable t :save-runtime-options nil
                            :toplevel #'sb-impl::toplevel-init))
(unless (find-package "SYSTEM") (defpackage "SYSTEM" (:use "COMMON-LISP") (:nicknames "SYS")))
(unless (find-package "SYS") (rename-package "SYSTEM" "SYSTEM" '("SYS")))
(in-package "CL-USER")
(defun sys::getenv (n) (sb-ext:posix-getenv n))
(defun sys::line-position (stream) (or (sb-impl::charpos (or stream *standard-output*)) 0))
(in-package "CL-USER")
