// Generated by tools/build.sh; do not hand edit.
export const WASM_HASHES={"32": "3829a34fc814de14c8efe90a02ec071836e0f08e380ee9848b152f55650df737", "32-single": "710954296779a344fe070dfc7b4ce20e7a468fed1672f115c4129a7aa30b31bf", "64": "4f4f95a7aec0e28b43ed4bdf0e976ba9e3f1bf405184d1ce509980f20bba496f", "64-single": "f83ee25c3ae11b10bf8b0506d65b95c50f323bc65a8835d73a66bbed070fc401"};
