import { TUTORIALS } from './tutorials.js';

// The original files are included in the downloadable George source archive.
export const GUIDE_SOURCES = [
  ['src/inout.sl', 'ALGFORMINPUT and algebraic input/output'],
  ['src/modes.sl', 'Fields, monomial orders, weights and processing modes'],
  ['auxil/topproc.sl', 'SIMPLE, HILBERT and top-level computation procedures'],
  ['src/anick/doc/anick_part_doc.body.tex', 'Original Anick user documentation'],
  ['src/anick/anbetti.sl', 'Internal-degree Betti table conventions'],
  ['src/anick/bnminout.sl', 'Module, factor-algebra and Hochschild input conventions'],
  ['tests/clisp/unix/clisp_list', 'The original sequential regression session'],
];

const text = {
  en: String.raw`
    <h1>User guide</h1>
    <p>George runs bergman and Fomkyr locally in your browser. Choose the implementation and its runtime settings under Engine; mathematical options are under More settings.</p>
    <nav class="guide-contents" aria-label="Engines and examples">
      <a href="#guide-bergman">Bergman</a><a href="#guide-bergman-fix">bergman-fix</a><a href="#guide-fomkyr">Fomkyr</a><a href="#guide-examples">Shared examples</a><a href="#guide-sources">Sources</a>
    </nav>
    <section id="guide-bergman"><h2>Bergman</h2>
    <p>This guide follows bergman 1.001's input routines, mode setters, Anick documentation and regression examples. George adds a browser form, cancellation and the documented corrections.</p>
    <p>The full manual, <a href="manual/bergman/manual.html" target="_blank" rel="noopener">Mathematical Computations Using Bergman</a> by Jörgen Backelin, Svetlana Cojocaru and Victor Ufnarovski, covers the original commands and algorithms. A local copy is included with George; the <a href="http://www.math.md/bergman/manual.html" target="_blank" rel="noopener">original is hosted on math.md</a>. The following introduction explains its use in George.</p>
    <nav class="guide-contents" aria-label="Guide sections">
      <a href="#guide-input">Input</a><a href="#guide-options">Fields and orders</a><a href="#guide-results">Results</a><a href="#guide-resolutions">Resolutions</a>
    </nav>
    <section id="guide-input"><h3>Enter a presentation</h3>
      <p>A noncommutative presentation describes \(A=k\langle x_1,\ldots,x_n\rangle/(f_1,\ldots,f_m)\); a commutative presentation uses \(k[x_1,\ldots,x_n]\). Enter the generators in order, then enter each relation as a polynomial equal to zero.</p>
      <ol><li>Choose a guided example below or enter generators such as <code>x, y</code>.</li><li>Enter expanded polynomials, separated by lines or commas: <code>x^2-y^2, xy</code>. This means \(x^2-y^2=0\) and \(xy=0\).</li><li>Choose a field, order, degree limit and computation; press Compute.</li><li>Open Files or Session to download the exact output and input commands.</li></ol>
      <p>The form accepts integer coefficients, nonnegative integer exponents and products using <code>*</code>. With single-letter generators, <code>xyx</code> means <code>x*y*x</code>. Longer names need explicit multiplication. Names are case sensitive: <code>x</code> and <code>X</code> differ. Commutators <code>[A,B]</code>, anticommutators <code>{A,B}</code> and one equals sign are expanded for you: <code>[a0,b0] = t^2</code> is read as <code>a0*b0-b0*a0-t^2</code>, and the expanded form appears under “Relations as read”. Round brackets are not expanded: write <code>x*y+x</code> for <code>x*(y+1)</code>. Trailing digits are shown as subscripts, so <code>b0</code> appears as <i>b</i><sub>0</sub>. Rational arithmetic is exact internally, but fractions and decimal coefficients are not form input syntax.</p>
      <p>In a free associative algebra, \(xy\ne yx\). Switching the Algebra control changes the algebra, rather than merely changing the display.</p>
    </section>
    <section id="guide-options"><h3>Fields, orders and degree limits</h3>
      <p>Choose \(\mathbb Q\), \(\mathbb F_2\) or \(\mathbb F_p\) with prime \(p\). Coefficients are reduced in the chosen field. A coefficient divisible by \(p\) vanishes, so changing the field can change the ideal and its basis.</p>
      <p>Generator order affects leading monomials, and the direction differs between bergman’s modes: the noncommutative degree orders rank the last listed generator highest, while the elimination orders and all commutative orders rank the first one highest. The line under the monomial order shows the order in effect, for example <i>y</i> &gt; <i>x</i>. The default associative order compares degree and then words from the left; the commutative default is degree reverse lexicographic. Reverse variable order, the elimination orders (noncommutative algebras) and the matrix order (commutative algebras) apply the corresponding bergman modes. A matrix must be square and nonsingular, with a positive first row in this interface.</p>
      <p>Weights must be positive integers, one per generator. The weighted degree is \(\deg(x_1^{a_1}\cdots x_n^{a_n})=\sum_i w_i a_i\). Relations such as <code>x^2-z</code> are homogeneous with weights <code>1, 2</code> for <code>x, z</code>.</p>
      <p>A maximal degree bounds the calculation; it does not prove that all higher critical pairs reduce to zero. An unbounded computation may never finish. Stop terminates the current worker, and the next computation starts a fresh session. Form computations are independent; Console commands retain their session.</p>
      <p>Engine offers Lisp / ECL O2, Lisp / ECL O3 + LTO, and C / ECL O3 + LTO, with a memory64 variant of the C engine. C / ECL O3 + LTO (memory64) is selected by default when supported: it compiles Bergman's Lisp functions to C and WebAssembly; some auxiliary functions still use bytecode. These variants use the same algebraic algorithms. The selection is saved and shared. Changing engines starts a new console session; earlier share links select O2.</p>
      <p>For large presentations, increase Memory limit under Engine. The default is 15.7 GiB (16077 MiB) with C / ECL O3 + LTO (memory64). Browsers without memory64 support start with the 32-bit C engine and 2 GiB. Existing saved settings and Share links preserve their choices. The 32-bit engines allow up to 4095 MiB (about 4 GiB); memory64 offers allowances up to 16 GiB and No heap cap. This last option removes George's heap allowance; the browser still limits this build to 16 GiB of total Wasm memory and may exhaust available memory earlier. The option requires a browser with memory64 support. Memory grows as needed; wider pointers can themselves use more memory. Saved basis output after OOM is partial, and the next command starts a fresh engine.</p>
      <p>Monomial pruning releases stored monomials after each completed degree. It is available for homogeneous noncommutative Gröbner bases without weights, using the default degreewise strategy. The option is saved and shared; incompatible settings turn it off. It can reduce retained memory, but the current degree still needs enough memory to finish.</p>
      <p>Time limit under Engine is measured in minutes. Its default, 0, allows computations to run without a time limit; you can always press Stop. A positive limit applies to each form computation and each console command, after the engine loads. Reaching it stops the worker and resets the console session. The limit is saved in preferences and share links.</p>
      <p>For nonhomogeneous relations choose automatic or itemwise processing. Default mode fixes the original nonhomogeneous reduction defects. Safe low-term handling accommodates constants and linear terms. Rabbit is an optional degree-jumping strategy; start with the ordinary strategy when comparing results.</p>
    </section>
    <section id="guide-results"><h3>Read and reproduce results</h3>
      <p>Share beside Compute copies a compact link to the presentation and all settings, including the memory limit, language and theme. Opening it restores the form; press Compute when ready. If copying is unavailable, copy the displayed link manually. Calculation times are shown in seconds.</p>
      <p>The Basis tab highlights the leading term of each printed polynomial and groups output by degree. Read its bound notice even when the raw file contains <code>Done</code>: a bounded calculation can still be partial.</p>
      <p>A Hilbert series records dimensions of graded components: \(H_A(t)=\sum_{d\ge0}\dim_k(A_d)t^d\). For an ordinary polynomial ring on \(n\) generators, \(H_A(t)=(1-t)^{-n}\); for an exterior algebra, \(H_A(t)=(1+t)^n\). Weighted inputs use weighted degrees. Hilbert and Poincaré–Betti computations are different tasks.</p>
      <p>Files contain the raw basis, series, resolution and, when applicable, <code>homology.json</code>. Session records <code>input.bg</code>, <code>session.lsp</code> and terminal output. Copy and Download preserve the original text. Display language and theme do not change any of these algebraic files.</p>
      <p>Download text results as ZIP adds <code>result-normalized.txt</code>: the reduced Gröbner basis through the computed degree. Every element is divided by its leading coefficient (exact fractions over \(\mathbb{Q}\)), no term of an element is divisible by another element's leading monomial, and elements and terms appear in a canonical order. The reduced basis is unique, so bergman and fomkyr produce the same file for the same presentation, order, field and bound.</p>
    </section>
    <section id="guide-resolutions"><h3>Anick resolutions and modules</h3>
      <p>For an Anick resolution, choose noncommutative algebra and an augmentation. Sending generators to 0 requires every relation's constant term to vanish. Sending generators to 1 requires the sum of its coefficients to vanish in the chosen field. For example, \(x^2-1\) admits the second augmentation. George then shifts \(x=u+1\) and labels the displayed resolution accordingly.</p>
      <p>For homogeneous relations, the printed Betti table's column \(i\) is homological degree and row \(r\) means internal degree \(i+r\). Its entry is \(\beta_{i,i+r}\); a dash means zero. The resolution view displays chains and their images in a tensor product.</p>
      <p>For nonhomogeneous relations, internal degree is not preserved. George first completes a basis, constructs the resolution and computes exact ranks of augmented differentials. The ungraded Betti numbers in <code>homology.json</code> are \(\beta_i=\dim C_i-\operatorname{rank}d_i-\operatorname{rank}d_{i+1}\). The original graded table alone is insufficient. Values are reported only where the incoming differential is available, or where a finite zero tail is certified.</p>
      <p>Longer names such as <code>x_1</code> and overlapping names such as <code>a</code> and <code>aa</code> are supported. George reads chains and exact coefficients from <code>resolution.jsonl</code>, a structural export using generator indices. A completed basis is required; increase the bound if completion cannot be certified.</p>
      <p>For right and left modules, module generators are the last generators listed. The two-module task uses the original left/right conventions. Factor-algebra and Hochschild tasks also have specialized variable conventions; start from their supplied regression presets. The original <code>bnminout.sl</code> describes the doubled variables and dummy generators. Do not treat arbitrary algebra relations as a module presentation.</p>
      <p>The Console evaluates complete Lisp forms such as <code>(GETSETUP)</code> and <code>(EXPT 3 40)</code>. It does not provide an interactive stdin dialogue between submissions. Use the presentation form or explicit file-based commands for polynomial input.</p>
      <p>Type <code>(help)</code> for the commands and <code>?name</code> for one of them, with bergman's own help text where it has one. Enter runs a form once its brackets balance and otherwise starts an indented line. Brackets are coloured by depth, the pair at the cursor is highlighted, and a grey suggestion completes command names (Tab accepts it). ↑ and ↓ browse the history, which is kept in this browser. <code>(files)</code> lists the session's files and <code>(show "out.gb")</code> prints one.</p>
    </section>
    </section>
    <section id="guide-bergman-fix"><h2>bergman-fix</h2>
      <p>George's Bergman engines use a corrected copy of bergman 1.001. The default mode fixes nonhomogeneous reduction, enforces the degree bound during itemwise processing, handles constant terms safely, and writes Poincaré–Betti output when immediate display is disabled. The original source files remain available in the source archive.</p>
      <p>Legacy mode restores the documented original computational branches, including their known defects and the historical empty PB file. Shared boundary corrections, such as terminating elimination-order comparisons, apply in both modes. Use the default mode for ordinary calculations; Legacy is useful when reproducing historical behavior.</p>
      <p>George also exports Anick chains with generator indices and exact coefficients, so longer and overlapping generator names work in the resolution display. These corrections apply across the Lisp and C/ECL variants.</p>
    </section>
    <section id="guide-fomkyr"><h2>Fomkyr</h2>
      <p><a href="./fomkyr/">Fomkyr manual</a>: capabilities, settings, output and the source subproject.</p>
      <p>Fomkyr is a separate C engine compiled with O3 and LTO. Select <strong>fomkyr</strong> under Engine. Its chooser entry is marked experimental. It computes homogeneous noncommutative Gröbner bases with 1–16 generators, ordinary degree and left lexicographic word order, over \(\mathbb Q\) or a prime field. Rational arithmetic is exact, including arbitrary-precision coefficients.</p>
      <p>Use the same <a href="#guide-input">presentation syntax</a> and <a href="#guide-results">result controls</a> as for Bergman. All terms of a relation must have the same degree; different relations may have different degrees. Leave weights blank or enter ones. Unsupported tasks and options are disabled. Commutative orders, nonunit weights, Anick resolutions, modules and the Lisp console require a Bergman engine.</p>
      <h3>Degree bounds and progress</h3>
      <p>Enter a maximal degree to compute a bounded basis; leave it blank to request completion. Time and memory allowances still apply. During a run, the display distinguishes the degree being processed from the last completed degree. Entering degree 12 means that work on degree 12 has started. Only its completion event certifies the result through degree 12. Overlap counts and sampled activity indicate ongoing work; they do not predict how much time remains.</p>
      <p>The Basis tab reports the completed bound and groups polynomials by degree and number of terms. A preview may show only part of a large result; use Show more or download the full basis from Files. A bounded basis is sufficient for the certified degrees. Unrestricted completion is reported separately when the engine proves it. Printed coefficients are normalized to primitive integers over \(\mathbb Q\); polynomial tails may remain unreduced.</p>
      <h3>Memory, workers and reduction settings</h3>
      <p>Engine contains the runtime controls and their <strong>?</strong> explanations. The Fomkyr memory allowance defaults to 3584 MiB when no allowance was supplied. Saved and shared settings retain their choices. The largest allowance is 14304 MiB. Automatic addressing chooses memory64 when needed; a browser fallback reports its effective limit. The memory display includes allocated Wasm workspaces. Browser, JavaScript and storage buffers use additional memory.</p>
      <table><thead><tr><th>Setting</th><th>How to use it</th></tr></thead><tbody>
        <tr><td>Execution and workers</td><td>Automatic uses shared multicore when the browser permits it, with a single-worker fallback. Choose a worker count to compare performance. More workers share the reduction pool and leave less workspace per worker.</td></tr>
        <tr><td>Reduction workspace</td><td>The automatic pool is 2048 MiB for allowances of 3584 MiB or more. A larger pool can accommodate harder rows, while leaving less memory for the stored basis and caches.</td></tr>
        <tr><td>Shared overflow workspace</td><td>Automatic reserves up to 512 MiB within the allowance for rational rows that outgrow a worker's workspace. Promoting a row without replay keeps its completed reduction work.</td></tr>
        <tr><td>Pairs per batch</td><td>The default is 128. Larger batches can keep workers busy; smaller batches reduce temporary memory. Zero selects the single-pair scheduler.</td></tr>
        <tr><td>Exact reduction and caches</td><td>The default enables sparse rational reduction, indexed word matching, local rewrites, radix queues and growth without replay. Cache and rewrite limits affect memory and speed. Their exact fallback paths preserve the requested algebra.</td></tr>
      </tbody></table>
      <p>Monomial pruning is enabled by default for Fomkyr. It uses proved square and commutation identities to discard zero terms. Eager pruning and quadratic pre-rewriting can prevent unnecessary terms from entering reduction queues. The chain criterion skips overlaps proved redundant by earlier compositions. Their benefit depends on the relations; increasing the degree can still increase time and memory sharply.</p>
      <h3>Checkpoints and Hilbert coefficients</h3>
      <p>Disk checkpoints store basis records and completed-degree progress in local browser storage. Resume matching checkpoint reuses a verified prefix for the same presentation, generator order and field. This can make a later run to a higher degree start near the previous bound. Disable resume when measuring a fresh run. Clearing site data removes checkpoints; a Share link reproduces settings and input without transferring those local files.</p>
      <p>Automatic file access probes the browser and uses a portable I/O owner when exclusive file handles are required. Compute workers remain parallel. If persistent storage is unavailable, the reported fallback uses bounded RAM.</p>
      <p>Enable Exact Hilbert coefficients under More settings to count normal words and obtain \(\dim_k A_d\). A blank Series degree uses the computed basis bound; a higher prefix requires a proved complete basis. Counting has its own workspace allowance. If optional counting cannot finish, the basis remains available. Fomkyr reports the exact coefficient prefix without inferring a rational formula for the full series.</p>
      <p>Known dimensions can shorten a run. If the normal words of a degree already number \(\dim_k A_d\), the remaining critical pairs of that degree reduce to zero and are skipped. The FK6 example uses its provided FK6 profile through degree 17. For other presentations, choose Dimension evidence under More settings and enter a series such as <code>1, 3, 6, 10</code>, “degree dimension” lines, a <code>hilbert.csv</code> from an earlier run, or a fomkyr JSON document. External dimensions are an assumption, so the result is marked Conditional. An integer-dual certificate is replayed against the original relations before use. Use one source of dimensions at a time.</p>
    </section>`,
  ru: String.raw`
    <h1>Руководство пользователя</h1>
    <p>George запускает bergman и Fomkyr локально в браузере. Ядро и параметры выполнения выбираются в меню «Движок», математические параметры — в дополнительных настройках.</p>
    <nav class="guide-contents" aria-label="Ядра и примеры">
      <a href="#guide-bergman">Bergman</a><a href="#guide-bergman-fix">bergman-fix</a><a href="#guide-fomkyr">Fomkyr</a><a href="#guide-examples">Общие примеры</a><a href="#guide-sources">Исходники</a>
    </nav>
    <section id="guide-bergman"><h2>Bergman</h2>
    <p>Руководство основано на процедурах ввода, настройках, документации Аника и тестовых примерах bergman 1.001. George добавляет браузерную форму, остановку вычислений и документированные исправления.</p>
    <p>Полное руководство <a href="manual/bergman/manual.html" target="_blank" rel="noopener">Mathematical Computations Using Bergman</a> Йоргена Бакелина, Светланы Кожокару и Виктора Уфнаровского описывает исходные команды и алгоритмы. Локальная копия включена в George; <a href="http://www.math.md/bergman/manual.html" target="_blank" rel="noopener">оригинал размещён на math.md</a>. Введение ниже объясняет его использование в George.</p>
    <nav class="guide-contents" aria-label="Разделы руководства">
      <a href="#guide-input">Ввод</a><a href="#guide-options">Поля и порядки</a><a href="#guide-results">Результаты</a><a href="#guide-resolutions">Резольвенты</a>
    </nav>
    <section id="guide-input"><h3>Задайте представление</h3>
      <p>Некоммутативное представление задаёт \(A=k\langle x_1,\ldots,x_n\rangle/(f_1,\ldots,f_m)\), коммутативное — фактор-алгебру \(k[x_1,\ldots,x_n]\). Укажите образующие в нужном порядке, затем введите соотношения как многочлены, равные нулю.</p>
      <ol><li>Выберите пример ниже или введите образующие, например <code>x, y</code>.</li><li>Введите раскрытые многочлены, разделяя их строками или запятыми: <code>x^2-y^2, xy</code>. Это означает \(x^2-y^2=0\) и \(xy=0\).</li><li>Выберите поле, порядок, предел степени и задачу; нажмите «Вычислить».</li><li>Во вкладках «Файлы» и «Сессия» можно скачать точный вывод и команды.</li></ol>
      <p>Форма принимает целые коэффициенты, неотрицательные целые показатели и произведения через <code>*</code>. Для однобуквенных образующих <code>xyx</code> означает <code>x*y*x</code>. Длинные имена разделяйте знаком умножения. Регистр важен: <code>x</code> и <code>X</code> различаются. Коммутаторы <code>[A,B]</code>, антикоммутаторы <code>{A,B}</code> и один знак равенства раскрываются автоматически: <code>[a0,b0] = t^2</code> читается как <code>a0*b0-b0*a0-t^2</code>, а раскрытая запись видна в разделе «Соотношения после разбора». Круглые скобки не раскрываются: вместо <code>x*(y+1)</code> введите <code>x*y+x</code>. Цифры в конце имени показываются индексом: <code>b0</code> выглядит как <i>b</i><sub>0</sub>. Внутренняя рациональная арифметика точная, однако дроби и десятичные коэффициенты не входят в синтаксис формы.</p>
      <p>В свободной ассоциативной алгебре \(xy\ne yx\). Переключатель типа алгебры меняет саму алгебру, а не только отображение.</p>
    </section>
    <section id="guide-options"><h3>Поля, порядки и предел степени</h3>
      <p>Выберите \(\mathbb Q\), \(\mathbb F_2\) или \(\mathbb F_p\) при простом \(p\). Коэффициенты вычисляются в выбранном поле. Кратный \(p\) коэффициент исчезает, поэтому изменение поля может изменить идеал и его базис.</p>
      <p>Порядок образующих влияет на старшие мономы, причём направление зависит от режима bergman: в некоммутативных порядках по степени старшей считается последняя образующая, а в исключающих и во всех коммутативных порядках — первая. Строка под мономиальным порядком показывает действующий порядок, например <i>y</i> &gt; <i>x</i>. Ассоциативный порядок по умолчанию сравнивает степень, затем слова слева; коммутативный — степень, затем обратный лексикографический порядок. Обратный порядок переменных, исключающие порядки (для некоммутативных алгебр) и матричный порядок (для коммутативных) включают соответствующие режимы bergman. В интерфейсе матрица должна быть квадратной и невырожденной, с положительной первой строкой.</p>
      <p>Веса — положительные целые числа, по одному на образующий. Взвешенная степень равна \(\deg(x_1^{a_1}\cdots x_n^{a_n})=\sum_i w_i a_i\). Соотношение <code>x^2-z</code> однородно при весах <code>1, 2</code> для <code>x, z</code>.</p>
      <p>Предел степени ограничивает вычисление, но не доказывает обращение в ноль всех старших критических пар. Неограниченное вычисление может не завершиться. «Стоп» завершает текущий worker; следующее вычисление получает новую сессию. Задачи формы независимы; команды консоли сохраняют состояние сессии.</p>
      <p>В меню «Движок» доступны Lisp / ECL O2, Lisp / ECL O3 + LTO и C / ECL O3 + LTO, включая вариант C с memory64. При наличии поддержки по умолчанию выбрано C / ECL O3 + LTO (memory64): оно компилирует Lisp-функции Bergman в C и WebAssembly; часть вспомогательных функций сохраняет байткод. Эти варианты используют одинаковые алгебраические алгоритмы. Выбор сохраняется в настройках и ссылке. Смена ядра начинает новый сеанс консоли; прежние ссылки выбирают O2.</p>
      <p>Для крупных систем увеличьте предел памяти в меню «Движок». По умолчанию выбрано C / ECL O3 + LTO (memory64) с пределом 15,7 ГиБ (16077 МиБ). Если браузер не поддерживает memory64, форма начинает с 32-битного ядра C и 2 ГиБ. Прежние сохранённые настройки и ссылки сохраняют свой выбор. 32-битные ядра допускают до 4095 МиБ (около 4 ГиБ); memory64 предлагает пределы до 16 ГиБ и режим без ограничения кучи. Последний снимает предел George; браузер всё ещё ограничивает эту сборку 16 ГиБ общей памяти Wasm и может исчерпать доступную память раньше. Нужен браузер с поддержкой memory64. Память выделяется по мере необходимости; более широкие указатели сами могут требовать больше памяти. Сохранённый после OOM вывод базиса частичный; следующая команда запускает новое ядро. Рядом с сообщением о вычислении показана выделенная память Wasm, обновляемая при её росте; это не вся RAM браузера и не объём живых Lisp-объектов.</p>
      <p>Очистка мономов освобождает сохранённые мономы после каждой завершённой степени. Она доступна для некоммутативных базисов Грёбнера с однородными соотношениями без весов и стандартной обработкой по степеням. Настройка сохраняется в браузере и ссылках; несовместимые параметры выключают её. Очистка может уменьшить занятую память, но текущей степени всё равно должно хватить памяти для завершения.</p>
      <p>Предел времени в меню «Движок» задаётся в минутах. По умолчанию он равен 0 — без ограничения; вычисление можно остановить кнопкой «Остановить». Положительный предел действует отдельно для каждого расчёта и каждой команды консоли после загрузки ядра. При его достижении движок останавливается, а сеанс консоли сбрасывается. Предел сохраняется в настройках и ссылке для отправки.</p>
      <p>Для неоднородных соотношений выберите автоматическую или поэлементную обработку. Режим по умолчанию исправляет исходные ошибки неоднородной редукции. Безопасная обработка младших членов учитывает константы и линейные члены. Rabbit — дополнительная стратегия со скачками по степени; для сравнения результатов начните с обычной стратегии.</p>
    </section>
    <section id="guide-results"><h3>Чтение и воспроизведение результатов</h3>
      <p>Кнопка «Поделиться» рядом с запуском вычисления копирует компактную ссылку на представление и все настройки, включая предел памяти, язык и тему. Ссылка восстанавливает форму; вычисление запускается отдельно. Если буфер обмена недоступен, скопируйте показанную ссылку вручную. Время расчёта отображается в секундах.</p>
      <p>Вкладка «Базис Грёбнера» выделяет старший член каждого многочлена и группирует вывод по степени. Читайте сообщение о пределе, даже если в исходном файле стоит <code>Done</code>: ограниченный расчёт может дать частичный базис.</p>
      <p>Ряд Гильберта задаёт размерности однородных компонент: \(H_A(t)=\sum_{d\ge0}\dim_k(A_d)t^d\). Для обычного кольца многочленов от \(n\) образующих \(H_A(t)=(1-t)^{-n}\), для внешней алгебры — \(H_A(t)=(1+t)^n\). При весах используются взвешенные степени. Ряды Гильберта и Пуанкаре–Бетти вычисляются разными задачами.</p>
      <p>Во вкладке «Файлы» доступны исходные базисы, ряды, резольвента и, когда применимо, <code>homology.json</code>. «Сессия» содержит <code>input.bg</code>, <code>session.lsp</code> и терминальный вывод. Копирование и скачивание сохраняют оригинальный текст. Язык и тема не меняют алгебраические файлы.</p>
      <p>«Скачать текстовые результаты в ZIP» добавляет <code>result-normalized.txt</code> — редуцированный базис Грёбнера до вычисленной степени. Каждый элемент поделён на старший коэффициент (точные дроби над \(\mathbb{Q}\)), ни один член элемента не делится на старший моном другого элемента, а элементы и члены идут в каноническом порядке. Редуцированный базис единственен, поэтому bergman и fomkyr дают одинаковый файл для одного задания, порядка, поля и предела.</p>
    </section>
    <section id="guide-resolutions"><h3>Резольвенты Аника и модули</h3>
      <p>Для резольвенты Аника выберите некоммутативную алгебру и аугментацию. При отображении образующих в 0 свободный член каждого соотношения должен исчезать. При отображении в 1 сумма коэффициентов должна исчезать в выбранном поле. Например, \(x^2-1\) допускает вторую аугментацию. George выполняет сдвиг \(x=u+1\) и помечает полученную резольвенту.</p>
      <p>Для однородных соотношений столбец \(i\) в таблице Бетти означает гомологическую степень, а строка \(r\) — внутреннюю степень \(i+r\). Элемент равен \(\beta_{i,i+r}\); тире означает ноль. В резольвенте показаны цепи и их образы в тензорном произведении.</p>
      <p>Для неоднородных соотношений внутренняя степень не сохраняется. George сначала пополняет базис, строит резольвенту и вычисляет точные ранги аугментированных дифференциалов. Неградуированные числа Бетти в <code>homology.json</code> равны \(\beta_i=\dim C_i-\operatorname{rank}d_i-\operatorname{rank}d_{i+1}\). Одной исходной градуированной таблицы недостаточно. Значения выдаются при наличии входящего дифференциала либо сертифицированного конечного нулевого хвоста.</p>
      <p>Поддерживаются длинные имена, например <code>x_1</code>, и имена с общим префиксом, например <code>a</code> и <code>aa</code>. George читает цепи и точные коэффициенты из <code>resolution.jsonl</code> — структурного экспорта с индексами образующих. Необходим завершённый базис; увеличьте предел, если завершённость не удалось подтвердить.</p>
      <p>Для правых и левых модулей образующие модуля находятся в конце списка. Задача для двух модулей следует исходным соглашениям о левых и правых образующих. Для фактор-алгебр и гомологий Хохшильда действуют отдельные соглашения: начните с готовых тестовых примеров. Исходный <code>bnminout.sl</code> описывает копии переменных и фиктивные образующие. Произвольные соотношения алгебры не являются представлением модуля.</p>
      <p>Консоль вычисляет законченные Lisp-формы, например <code>(GETSETUP)</code> и <code>(EXPT 3 40)</code>. Между отправками она не ведёт интерактивный диалог stdin. Для многочленов используйте форму или команды с явными файлами.</p>
      <p><code>(help)</code> выводит список команд, <code>?имя</code> — описание одной из них вместе с собственной справкой bergman, если она есть. Enter выполняет форму, когда скобки сбалансированы, а иначе начинает новую строку с отступом. Скобки окрашены по глубине, пара у курсора подсвечена, серая подсказка дополняет имена команд (Tab её принимает). ↑ и ↓ листают историю, которая хранится в этом браузере. <code>(files)</code> выводит список файлов сеанса, <code>(show "out.gb")</code> — содержимое файла.</p>
    </section>
    </section>
    <section id="guide-bergman-fix"><h2>bergman-fix</h2>
      <p>Ядра Bergman в George используют исправленную копию bergman 1.001. Режим по умолчанию исправляет неоднородную редукцию, соблюдает предел степени при поэлементной обработке, безопасно обрабатывает константы и записывает ряд Пуанкаре–Бетти при отключённом немедленном выводе. Исходные файлы доступны в архиве исходников.</p>
      <p>Режим совместимости возвращает документированные исходные ветви вычислений, включая известные ошибки и исторически пустой PB-файл. Общие исправления граничных случаев, например завершение сравнений в исключающих порядках, действуют в обоих режимах. Для обычных расчётов используйте режим по умолчанию; совместимость полезна для воспроизведения исторического поведения.</p>
      <p>George также экспортирует цепи Аника с индексами образующих и точными коэффициентами, поэтому длинные имена и имена с общим префиксом поддерживаются при отображении резольвенты. Эти исправления действуют во всех вариантах Lisp и C/ECL.</p>
    </section>
    <section id="guide-fomkyr"><h2>Fomkyr</h2>
      <p><a href="./fomkyr/">Руководство Fomkyr (EN)</a>: возможности, параметры, результаты и подпроект с исходниками.</p>
      <p>Fomkyr — отдельное ядро на C, собранное с O3 и LTO. Выберите <strong>fomkyr</strong> в меню «Движок». В списке ядер оно помечено как экспериментальное. Оно вычисляет однородные некоммутативные базисы Грёбнера с 1–16 образующими, обычной степенью и левым лексикографическим порядком слов над \(\mathbb Q\) или простым конечным полем. Рациональная арифметика точная, включая коэффициенты произвольной точности.</p>
      <p>Используйте общий <a href="#guide-input">синтаксис представлений</a> и <a href="#guide-results">средства работы с результатами</a>. Все члены одного соотношения должны иметь одинаковую степень; разные соотношения могут иметь разные степени. Оставьте веса пустыми или укажите единицы. Неподдерживаемые задачи и настройки отключены. Для коммутативных порядков, неединичных весов, резольвент Аника, модулей и Lisp-консоли выберите ядро Bergman.</p>
      <h3>Предел степени и ход вычисления</h3>
      <p>Укажите максимальную степень для ограниченного расчёта; пустое поле запрашивает полное завершение. Пределы времени и памяти продолжают действовать. Во время расчёта отображаются текущая степень и последняя завершённая степень. Переход к степени 12 означает начало работы над ней. Только событие завершения подтверждает результат до степени 12 включительно. Счётчики перекрытий и активности показывают ход работы, но не предсказывают оставшееся время.</p>
      <p>Вкладка «Базис Грёбнера» сообщает завершённую степень и группирует многочлены по степени и числу членов. Предпросмотр крупного результата может содержать только его часть; нажмите «Показать ещё» или скачайте полный базис во вкладке «Файлы». Ограниченный базис достаточен для подтверждённых степеней. Полное завершение без ограничения отмечается отдельно, когда ядро его доказывает. Над \(\mathbb Q\) коэффициенты приводятся к взаимно простым целым; хвосты многочленов могут оставаться неприведёнными.</p>
      <h3>Память, потоки и настройки редукции</h3>
      <p>Меню «Движок» содержит параметры выполнения и пояснения под знаком <strong>?</strong>. Если предел памяти не задан, Fomkyr использует 3584 МиБ. Сохранённые настройки и ссылки сохраняют выбранный предел. Максимум — 14304 МиБ. Автоматический выбор адресации включает memory64 при необходимости; при откате браузер сообщает фактический предел. Индикатор памяти включает выделенные рабочие области Wasm. Браузер, JavaScript и буферы хранилища занимают дополнительную память.</p>
      <table><thead><tr><th>Настройка</th><th>Как её использовать</th></tr></thead><tbody>
        <tr><td>Выполнение и потоки</td><td>Автоматический режим использует несколько потоков при поддержке браузером, иначе один worker. Можно выбрать число потоков для сравнения скорости. Потоки делят общий пул редукции; при увеличении их числа на каждый остаётся меньше рабочего пространства.</td></tr>
        <tr><td>Рабочая область редукции</td><td>Автоматический пул составляет 2048 МиБ при пределе памяти от 3584 МиБ. Увеличение пула помогает вместить сложные строки, оставляя меньше памяти для базиса и кешей.</td></tr>
        <tr><td>Общая резервная область</td><td>Автоматически выделяется до 512 МиБ внутри общего предела для рациональных строк, которые переросли рабочую область потока. Перенос без повторной редукции сохраняет уже выполненную работу.</td></tr>
        <tr><td>Пар в пакете</td><td>По умолчанию 128. Большие пакеты могут полнее загрузить потоки, меньшие сокращают временную память. Ноль включает обработку по одной паре.</td></tr>
        <tr><td>Точная редукция и кеши</td><td>По умолчанию включены разреженная рациональная редукция, индекс слов, локальные переписывания, radix-очередь и рост без повторной обработки. Пределы кешей и переписываний влияют на память и скорость; точные резервные алгоритмы сохраняют заданную алгебру.</td></tr>
      </tbody></table>
      <p>Очистка мономов для Fomkyr включена по умолчанию. Она использует доказанные тождества для квадратов и перестановок, чтобы отбрасывать нулевые члены. Ранняя очистка и квадратичное переписывание могут исключать лишние члены до помещения в очередь редукции. Цепной критерий пропускает перекрытия, избыточность которых следует из ранее обработанных композиций. Польза зависит от соотношений; рост степени всё ещё может резко увеличивать время и память.</p>
      <h3>Контрольные точки и коэффициенты Гильберта</h3>
      <p>Дисковые контрольные точки сохраняют базис и прогресс завершённых степеней в локальном хранилище браузера. Продолжение подходящей контрольной точки использует проверенный начальный участок для того же представления, порядка образующих и поля. Поэтому следующий расчёт до большей степени может начать около прежнего предела. Для измерения расчёта с нуля отключите продолжение. Очистка данных сайта удаляет контрольные точки; ссылка «Поделиться» передаёт настройки и ввод без локальных файлов.</p>
      <p>Автоматический доступ к файлам проверяет возможности браузера и использует отдельного владельца ввода-вывода, если требуются эксклюзивные файловые дескрипторы. Вычислительные потоки продолжают работать параллельно. Если постоянное хранилище недоступно, используется указанный в сообщении режим с ограниченной RAM.</p>
      <p>Включите точные коэффициенты Гильберта в дополнительных настройках для подсчёта нормальных слов и получения \(\dim_k A_d\). Пустое поле степени ряда использует вычисленный предел базиса; более длинный участок требует доказанного полного базиса. Для подсчёта предусмотрен отдельный предел рабочей памяти. Если дополнительный подсчёт не завершился, базис остаётся доступен. Fomkyr выдаёт точный начальный участок коэффициентов без вывода рациональной формулы полного ряда.</p>
      <p>Известные размерности могут сократить вычисление. Если число нормальных слов степени уже равно \(\dim_k A_d\), оставшиеся критические пары этой степени сводятся к нулю и пропускаются. Пример FK6 использует встроенный профиль FK6 до степени 17. Для других заданий выберите «Данные о размерностях» в дополнительных настройках и введите ряд, например <code>1, 3, 6, 10</code>, строки «степень размерность», <code>hilbert.csv</code> прежнего вычисления или JSON-документ fomkyr. Внешние размерности — допущение, поэтому результат помечается как условный. Целочисленный сертификат перед использованием проверяется на исходных соотношениях. Используйте один источник размерностей.</p>
    </section>`,
};

export function guideHTML(language) {
  const ru = language === 'ru';
  language = ru ? 'ru' : 'en';
  return text[language].replace('<h1>', '<h1 id="guideTitle">') + `<section id="guide-examples"><h2>${ru ? 'Общие примеры' : 'Shared examples'}</h2>
    <p>${ru ? 'Примеры используют общий формат ввода. Однородные некоммутативные примеры с единичными весами можно вычислять обоими ядрами. Для остальных выберите Bergman; выбранное ядро сохраняется при загрузке примера, а несовместимые параметры отмечаются в форме.' : 'Examples use the shared input format. Homogeneous noncommutative examples with unit weights can run on either engine. Choose Bergman for the others; loading an example preserves the engine selection, and the form identifies incompatible settings.'}</p>
    <div class="example-cards">${TUTORIALS.map(t => `<article><h3>${t.title[language]}</h3><p>${t.description[language]}</p>${t.source ? `<p><a href="${t.source.url}" target="_blank" rel="noopener">${t.source.title}</a></p>` : ''}<button type="button" class="quiet" data-tutorial="${t.id}">${ru ? 'Открыть пример' : 'Load example'}</button></article>`).join('')}</div></section>
    <section id="guide-sources"><h2>${ru ? 'Исходные материалы' : 'Original source material'}</h2><p>${ru ? 'Перечисленные исходные материалы Bergman находятся в архиве George. Ссылка на полное руководство приведена в разделе Bergman.' : 'The listed Bergman source material is included in the George source archive. The Bergman section links to the full manual.'}</p>
    <ul>${GUIDE_SOURCES.map(([p]) => `<li><code>vendor/bergman-1.001/${p}</code></li>`).join('')}</ul>
    <p><a href="sources/george-source.tar.gz">${ru ? 'Скачать исходники George и bergman' : 'Download George and bergman sources'}</a></p></section>`;
}
