#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
CLANG=${CLANG:-clang}
mkdir -p dist
COMMON=(-std=c11 -O3 -flto -ffreestanding -fno-builtin -fvisibility=hidden -Wall -Wextra)
CLANG="$CLANG" python3 tools/prepare-wasm-profile.py
WASM_PROFILE=()
if python3 -c 'import json,sys;sys.exit(not json.load(open("dist/wasm-compiler.json"))["pgo"])'; then
  WASM_PROFILE=(-fprofile-instr-use=dist/wasm-pgo.profdata -Werror=profile-instr-out-of-date -Werror=profile-instr-unprofiled)
fi
for bits in 32 64; do
  max=4294901760
  [[ $bits == 64 ]] && max=14999945216
  for mode in shared single; do
    name=fomkyr${bits}; flags=(-mbulk-memory)
    if [[ $mode == shared ]]; then flags+=(-matomics -Wl,--shared-memory); else name+=-single; flags+=(-DGN_SINGLE); fi
    "$CLANG" --target=wasm${bits} "${COMMON[@]}" "${WASM_PROFILE[@]}" "${flags[@]}" -nostdlib \
      src/kernel.c -o dist/${name}.wasm \
      -Wl,--no-entry,--import-memory,--export-dynamic,--export=__stack_pointer \
      -Wl,--initial-memory=2097152,--max-memory="$max",-z,stack-size=131072,--lto-O3
  done
done
"$CLANG" "${COMMON[@]}" -fvisibility=default -fPIC -shared src/kernel.c tests/host.c -o dist/libfomkyr.so -fuse-ld=lld
for name in fomkyr32 fomkyr64 fomkyr32-single fomkyr64-single; do cp "dist/$name.wasm" web/; done
python3 - <<'GEN'
import hashlib,json
from pathlib import Path
h={f'{b}{suffix}':hashlib.sha256(Path(f'dist/fomkyr{b}{suffix}.wasm').read_bytes()).hexdigest() for b in (32,64) for suffix in ('','-single')}
Path('web/build-info.js').write_text('// Generated by tools/build.sh; do not hand edit.\nexport const WASM_HASHES='+json.dumps(h)+';\n')
with Path('web/build-info.js').open('a') as f:
    f.write('export const WASM_COMPILER='+json.dumps(json.loads(Path('dist/wasm-compiler.json').read_text()))+';\n')
GEN
