#!/usr/bin/env python3
"""Memory-bounded independent exact same-degree tail normalization.
Requires the independently scanned proper-subword precondition. Neither this nor
canonical equality is a full Groebner certificate. Canonical cache is private,
ephemeral data generated by this process; no untrusted pickle input is accepted.
"""
from pathlib import Path
from fractions import Fraction
from collections import OrderedDict
import argparse,subprocess,sys,json,struct,hashlib,tempfile,pickle,sqlite3,time,gc
R=Path(__file__).resolve().parents[1]
def canon(file,D,variables,out,cache_bytes=128<<20):
 with tempfile.TemporaryDirectory(prefix='fomkyr-canon-')as td:
  td=Path(td);index=td/'index.tsv';checker=R/'dist/packed-basis-audit'
  q=subprocess.run([str(checker),str(file),str(D),str(len(variables)),str(index)],capture_output=True,text=True,timeout=180);assert not q.returncode,q.stderr;checks=json.loads(q.stdout)
  rows={};bydegree={}
  for line in index.read_text().splitlines():
   i,d,off,size,n,lm=line.split();i,d,off,size,n=int(i),int(d),int(off),int(size),int(n);lm=int(lm,16);rows[i]=(d,off,size,n,lm);bydegree.setdefault(d,{})[lm]=i
  db=sqlite3.connect(td/'cache.sqlite');db.execute('PRAGMA journal_mode=OFF');db.execute('PRAGMA synchronous=OFF');db.execute('CREATE TABLE rows (id INTEGER PRIMARY KEY,p BLOB)');cache=OrderedDict();charged=0
  def get(i):
   nonlocal charged
   if i in cache:cache.move_to_end(i);return cache[i][0]
   got=db.execute('SELECT p FROM rows WHERE id=?',(i,)).fetchone();assert got is not None,'triangular dependency missing';return pickle.loads(got[0])
  stream=out.open('wb');digest=hashlib.sha256()
  def emit(x):
   b=(json.dumps(x,separators=(',',':'),sort_keys=True)+'\n').encode();stream.write(b);digest.update(b)
  emit(dict(format='fomkyr-packed-canonical-q-v1',variables=variables,throughDegree=D,order='degleftlex-last-variable-largest',modulus=0,independentGroebnerCertificate=False,wordEncoding='hex, zero-padded to row degree; each digit is a generator index'))
  with file.open('rb')as src:
   for i in sorted(rows,key=lambda i:(rows[i][0],rows[i][4])):
    d,off,size,n,lm=rows[i];src.seek(off);data=src.read(size);assert len(data)==size
    def coefficient(code):
     if code&1:
      pos=code&~7;k=struct.unpack_from('<I',data,pos)[0];v=int.from_bytes(data[pos+8:pos+8+4*k],'little');return -v if code&2 else v
     return (code if code<(1<<63)else code-(1<<64))>>1
    lead=coefficient(struct.unpack_from('<Q',data,48)[0]);result={lm:1}
    for j in range(1,n):
     lo,hi,c=struct.unpack_from('<QQQ',data,32+j*24);w=lo|(hi<<64);c=coefficient(c);c=c//lead if c%lead==0 else Fraction(c,lead)
     child=bydegree[d].get(w)
     if child is not None:
      assert w<lm;tail=get(child)
      for v,b in tail.items():
       if v==w:continue
       x=result.get(v,0)-c*b
       if x:result[v]=x
       else:result.pop(v,None)
     else:
      x=result.get(w,0)+c
      if x:result[w]=x
      else:result.pop(w,None)
    assert all(w==lm or w not in bydegree[d] for w in result)
    if len(result)>2_000_000:raise ValueError('canonical row exceeded audit budget')
    packed=pickle.dumps(result,protocol=5);db.execute('INSERT INTO rows VALUES (?,?)',(i,packed));cost=256+len(result)*192
    while cache and charged+cost>cache_bytes:
     _,(_,old)=cache.popitem(last=False);charged-=old
    if cost<=cache_bytes:cache[i]=(result,cost);charged+=cost
    emit([[format(w,f'0{d}x'),str(c)]for w,c in sorted(result.items(),reverse=True)])
    if i%512==0:print('normalized',i,'degree',d,'terms',len(result),file=sys.stderr,flush=True)
  stream.close();db.close();return dict(**checks,canonicalSHA256=digest.hexdigest(),canonicalBytes=out.stat().st_size,coefficientArithmetic='Python integers/Fraction',canonicalCacheLimit=cache_bytes)
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('fixture',type=Path);p.add_argument('basis',type=Path);p.add_argument('--against',type=Path);p.add_argument('--degree',type=int,required=True);p.add_argument('--out',type=Path,required=True);p.add_argument('--canonical',type=Path);a=p.parse_args();variables=json.loads(a.fixture.read_text())['variables'];start=time.perf_counter();report=dict(degree=a.degree,independentGroebnerCertificate=False,kind='independent proper-subword checks plus exact triangular canonical comparison',files=[])
 try:
  with tempfile.TemporaryDirectory(prefix='fomkyr-canon-compare-')as td:
   paths=[]
   for j,f in enumerate([a.basis]+([a.against]if a.against else[])):
    out=Path(td)/str(j);x=canon(f,a.degree,variables,out);report['files'].append(dict(file=str(f),**x));paths.append(out);gc.collect()
   if len(paths)==2:
    with paths[0].open('rb')as x,paths[1].open('rb')as y:
     while True:
      left,right=x.read(1<<20),y.read(1<<20);assert left==right,'canonical byte streams differ'
      if not left:break
    report['exactCanonicalBytesEqual']=True
   if a.canonical:
    import shutil;shutil.copyfile(paths[0],a.canonical)
  report['passed']=True
 except Exception as e:report.update(passed=False,error=str(e))
 report['elapsedSeconds']=time.perf_counter()-start;a.out.parent.mkdir(parents=True,exist_ok=True);a.out.write_text(json.dumps(report,indent=2));print(json.dumps(report));sys.exit(0 if report['passed']else 1)
if __name__=='__main__':main()
